[workspace]

members = [
    "ray-tracer-challenge",
    "ray-tracing-one-weekend"
]
resolver = "2"

[profile.dev-raytrace]
inherits = "dev"
opt-level = 1

[profile.bench]
debug = true

[profile.release]
lto = "fat"
codegen-units = 1
